spring.application.name=backend-spring
server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/digitallibrary?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=123456

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jackson.time-zone=Asia/Ho_Chi_Minh

jwt.secret=ngocsome-spring-boot-react-mysql-secret-key-123456789
jwt.expiration=86400000

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=60MB